import pygame, pyautogui, time
pygame.init()
w,h=pyautogui.size()
screen=pygame.display.set_mode((w,h))
pygame.display.set_caption("christmas card")
bg1=pygame.image.load("igloo.png")
santa=pygame.image.load("santa.png")
santa=pygame.transform.scale(santa,(300,300))
sleigh=pygame.transform.scale(pygame.image.load("sleigh.png"),(300,300))
snowman=pygame.transform.scale(pygame.image.load("snowman.png"),(300,300))
tree=pygame.transform.scale(pygame.image.load("tree.png"),(300,300))
bg2=pygame.image.load("skilodge.png")
bg3=pygame.image.load("treehouse.png")

font1=pygame.font.SysFont("Comic sans",100,True)
font2=pygame.font.SysFont("Arial",70,True)
font3=pygame.font.SysFont("Arial black",50,True)
font4=pygame.font.SysFont("Roboto mono",120,True)
text1=font1.render("Merry Christmas",True,"red")
text2=font2.render("Wishing you all",True,"green")
text3=font3.render("Get well soon",True,"cyan")
text4=font4.render("2026!!",True,"black")
text1=pygame.transform.rotate(text1,-45)
text2=pygame.transform.rotate(text2,45)

# text1=pygame.transform.flip(text1,False,True)
# text2=pygame.transform.flip(text2,True,True)
count=0
while True:
    count+=1
    for i in pygame.event.get():
        print(i)
        if i.type==pygame.QUIT:
            pygame.quit()
    screen.fill("white")
    # for i in pygame.event.get():
    #     print(i)
    #     if i.type==pygame.QUIT:
    #         pygame.quit()
    screen.blit(bg3,(200,0))
    pygame.display.update()
    time.sleep(1)
    screen.blit(text1,(300,100))
    screen.blit(text2,(w-800,200))
    screen.blit(text3,(w-800,))
    screen.blit(text4,(w-800,300))

    pygame.display.update()
    time.sleep(1)
    screen.blit(tree,(200,h/2))
    pygame.display.update()
    time.sleep(1)
    screen.blit(santa,(w/2,h/2))
    pygame.display.update()
    time.sleep(1)
    screen.blit(sleigh,(w/2+100,h/2+200))
    pygame.display.update()
    time.sleep(1)
    screen.blit(bg1,(200,0))
    pygame.display.update()
    time.sleep(1)
    screen.blit(bg2,(200,0))
    pygame.display.update()
    time.sleep(1)
    screen.blit(snowman,(w/2,h/2))
    pygame.display.update()
    time.sleep(1)
    screen.blit(sleigh,(w/2+100,h/2+200))
    pygame.display.update()
    time.sleep(1)
  